### ISSUE TITLE
vyos_firewall_rules doesn't appear to be stable

### ISSUE THREAD

**Issue by pabelanger** [ansible-collections/vyos.vyos#11]
##### SUMMARY

It seems like we have a race condition for vyos_firewall_rules. We need to properly fix.

https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_10/10/2fa14b5c9958b8c2d755614ca729aded68e1b348/check/ansible-test-network-integration-vyos-python27/b7a4072/controller/ara-report/

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by rohitthakur2590** [comment]
Haven't seen this after successive runs, the fact that it was for after dict assertion lets keep an eye on this.
