### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by istaicu** [ansible-collections/vyos.vyos#18]
##### SUMMARY
In https://github.com/ansible/ansible/tree/stable-2.9/lib/ansible/plugins/terminal, there was a file called cnos.py, but on the devel branch they aren't present anymore, as you can see: https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins. 
Next to the "terminal" folder it says "Migrated to vyos.vyos" and no file can be found in that folder anymore. If you click on that you find this submit https://github.com/ansible/ansible/pull/68282 which deleted many files in the project.
I guess this is the new repository the file should be in (https://github.com/ansible-collections/vyos/), but I'm unable to find it. Nor any of the other files in this folder..

And also, I can't find the files in 
https://github.com/ansible/ansible/tree/stable-2.9/lib/ansible/modules/network/cnos
Were they supposed to be moved under https://github.com/ansible-collections/ ? because I don't see the cnos folder.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
modules/network/cnos
terminal plugin

**Comment by Qalthos** [comment]
This has nothing to do with this repository. The message "Migrated to vyos.vyos" is just the latest commit on that folder, and does not indicate where _everything_ in that folder went.

In this case, the cnos terminal plugin (along with the rest of the cnos files) moved to https://github.com/ansible-collections/community.network (https://github.com/ansible-collections/community.network/tree/master/plugins/terminal/cnos.py) as there is no cnos-specific collection.

**Comment by istaicu** [comment]
Thank you very much :)
