### ISSUE TITLE
[vyos_ntp_global] `dynamic` isn't a valid vyos option for a server, and `pool` is missing

### ISSUE THREAD

**Issue by sdwilsh** [ansible-collections/vyos.vyos#221]
##### SUMMARY

#175 added `vyos_ntp_global`, which allows setting `options` on `servers`.  Per the documentation, those options are `noselect`, `dynamic`, `preempt`, and `prefer`.  However, documentation for [equuleus](https://docs.vyos.io/en/equuleus/configuration/system/ntp.html) and [dev](https://docs.vyos.io/en/latest/configuration/system/ntp.html) do not have `dynamic`, but instead `pool` ([crux](https://docs.vyos.io/en/crux/configuration/system/ntp.html) documentation is lacking clarity).  `dynamic` is not a supported option for vyos, so it's impossible to set a pool with this module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`vyos.vyos.vyos_ntp_global`

##### STEPS TO REPRODUCE

```yaml
    - vyos.vyos.vyos_ntp_global:
        config:
          servers:
            - server: "0.pool.ntp.org"
              options:
                - "dynamic"
```

##### EXPECTED RESULTS

All documented options to work, and all options to be allowed for a server.  I would find it acceptable if `dynamic` maps to `pool` if this module is trying to maintain compatibility with out networking modules, but that should be documented as well.

##### ACTUAL RESULTS

If you use the above example, you get an error (tested on equuleus):
```
Configuration path: system ntp server 0.pool.ntp.org [dynamic] is not valid
```

If you try to manually specify `pool` an an option, you get an error:
```
value of options must be one or more of: noselect, dynamic, preempt, prefer. Got no match for: pool found in config -> servers
```

**Comment by sdwilsh** [comment]
I'm happy to make a patch for this, but it's not clear to me if we want to keep the API using `dynamic` and replace it with `pool` on device, or if we want to replace `dynamic` in the API with `pool`.

**Comment by GomathiselviS** [comment]
Hi @sdwilsh We have been using `helium` and `equuleus` for developing and testing the module. Though helium has reached its EOL, inorder to provide backward compatibility, I have added the `dynamic` option under server. I would like to hold on to it. I shall add a new parameter `pool` under server , in order to support the configuration in crux and sagitta. Please let me know your views.

**Comment by GomathiselviS** [comment]
@sdwilsh Can you please review #225  ?
