### ISSUE TITLE
[VyOS]: Update old resource modules with new states

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/vyos.vyos#24]
##### SUMMARY

Add `gathered`, `rendered`, `parsed` support to the following RMs:
  - [x] vyos_interfaces: https://github.com/ansible-collections/vyos.vyos/pull/25
  - [x] vyos_l3_interfaces: https://github.com/ansible-collections/vyos.vyos/pull/26
  - [x] vyos_lag_interfaces: https://github.com/ansible-collections/vyos.vyos/pull/27
  - [x] vyos_lldp_interfaces: https://github.com/ansible-collections/vyos.vyos/pull/28
  - [x] vyos_lldp_global : https://github.com/ansible-collections/vyos.vyos/pull/29
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by trishnaguha** [comment]
Please take care of adding fully qualified collection name in the examples for these modules in the same PRs as well.
