### ISSUE TITLE
Removal from Ansible Community Package

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/vyos.vyos#344]
There has been an announcement deprecating this collection in [The Bullhorn #123](https://forum.ansible.com/t/2568). It says there won't be any more major releases, but I don't see any minor or even bugfix releases either for quite some time.

This repo isn't archived and there is no information about deprecation neither in the repo nor on [galaxy](https://galaxy.ansible.com/ui/repo/published/vyos/vyos/). However, because of the deprecation announcement there is now a discussion about [removing this collecection from the Ansible Community Package](https://forum.ansible.com/t/6244).

At least one month after this announcement appears here and on [Bullhorn](https://forum.ansible.com/c/news/bullhorn/17), the Ansible Community Steering Committee will vote on whether this collection will be removed, or whether it will be kept. If it will be removed, this will happen earliest in Ansible 11. Please note that people can still manually install the collection with `ansible-galaxy collection install vyos.vyos` even when it has been removed from Ansible.

**Comment by dmbaturin** [comment]
VyOS maintainer here.

There are some considerations about VyOS support for ansible:

First, this module pre-dates a proper API in VyOS and had to manage it by sending commands over SSH. We've had a REST(ish) API since 1.2 (2019) and now we have a GraphQL API with an automatically generated schema and JWT tokens, so it's a lot easier to create integrations.

But it will basically take a new module to do that.

In light of this module getting deprecated and those new developments in VyOS, my main question is: what's the best way we can help?

If we write a module, can it become the new `vyos.vyos`? Or would it need to use a different name even after removal? Or can we become maintainers of this one and try a more gradual rewrite?

**Comment by mariolenz** [comment]
@dmbaturin I'm not always sure what you're talking about. It looks like you mix up some terminology:

> First, this module pre-dates [...]
> 
> But it will basically take a new module to do that.
> 
> In light of this module getting deprecated

`vyos.vyos` isn't a _module_, it's an Ansible _collection_ containing several modules (and maybe some other stuff, I don't really know it :shrug:) .

I want to make clear that I'm not responsible for this collection and didn't deprecate it. This issue is simply about removing it from the [Ansible Community Package](https://pypi.org/project/ansible/) (ACP) since it _has_ been deprecated. Not about removing from galaxy or GitHub or anything else. The future of this collection (as long as it isn't the future as being a part of ACP) isn't in my hands.

> and those new developments in VyOS, my main question is: what's the best way we can help?
> 
> If we write a module, can it become the new `vyos.vyos`? Or would it need to use a different name even after removal? Or can we become maintainers of this one and try a more gradual rewrite?

A single module is not a collection (see above). Anyway, I think if you want to start a new collection under the old name might be problematic. At the very least, there's the question about permissions on [galaxy](https://galaxy.ansible.com/ui/repo/published/vyos/vyos/) and I don't really know how to give them to you. Maybe fork the repo and try to convince people that you're the new real `vyos.vyos` collection?

I'm also not sure how you could take over ownership / maintainership of the current repository. I guess it would need the cooperation of the current maintainers, but since this collection is unmaintained I see a problem there...

BTW I think it would be better to move this discussion [to the forum](https://forum.ansible.com/t/6244). I hope we'll get more reactions / help / info there.

**Comment by NilashishC** [comment]
@mariolenz I've commented on the forum discussion regarding the current state, like ovs.ovs and frr.frr.

@dmbaturin We would be glad to have you officially maintain this collection. Please let me know how to reach out to you for discussing the specifics. Thank you!

**Comment by gaige** [comment]
@dmbaturin If you're looking for some assistance, I'm interested. I've been doing a bunch of work on a private copy of `vyos.vyos` with the original intention of contributing the changes to deal with 1.3, 1.4 and 1.5 simultaneously as well as adding support for some additional features that aren't configured in the current modules.  I'd be happy to collaborate on moving to an API-based version. 

I've already done some significant work on firewall, interface, ospf, and routes modules. (fork is poorly-named, but https://github.com/cluetrust/vyos.vyos/tree/fix-banners).

**Comment by gundalow** [comment]
Hey,
Ansible & VyOS teams met today.
Just a quick update from Ansible Engineering. Happy to announce that the existing `vyos.vyos` collection will move over and be maintained by the VyOS team.
We’ve got a few things to tidy up (including removing the deprecation notice) then we will release a new version of the collection.
The collection WILL be staying in the `ansible` community package.

**Comment by mariolenz** [comment]
Cool! I would still like to keep this open for now.

How about adding `Fixes #344` to the next release PR? This way, we can keep it open for now but don't have to remember closing it manually.

**Comment by sdwilsh** [comment]
I'm also interested in improving this collection.  I have contributed PRs here in the past (still have one open, even), and it's how I used to get access to vyos stable builds until things stopped getting reviewed/merged here.
