### ISSUE TITLE
Redundancy vyos_ prefix for plugins while already in vyos collection

### ISSUE THREAD

**Issue by bmillemathias** [ansible-collections/vyos.vyos#62]
##### SUMMARY
That would be less redundant to strip the vyos_ prefix from the plugins name,

#### ISSUE TYPE
- Bug Report

**Comment by GomathiselviS** [comment]
@bmillemathias  As mentioned in the junos collection PR, following is the reason for holding on to the prefix vyos_

We have to keep the vyos_ for modules for backward compatibility as these collections are part of Ansible Community Distribution (ACD) Refer https://groups.google.com/forum/#!topic/ansible-devel/NoYmrpQ3IkU. In the long term, we do have plans to move to use the short name for plugins.

Currently, the long plugin name (eg. vyos.vyos.vyos_config) is redirected to the short name (eg. jvyos.vyos.config) using runtime.yml file which is part of the collection. So you can use the short names in your playbook with ansible-base 2.10 release.
